apiVersion: v1
kind: Service
metadata:
  name: powerplatform-service
spec:
  type: NodePort
  selector:
    app: powerplatform-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
